export { default as Home } from './Home/Home';
export { default as LoadInit } from './Load/LoadInit';
export { default as User } from './User/User';
export { default as NotFound } from './Error/NotFound';
export { default as Help } from './Help/Help';
export { default as Questions } from './Questions/Questions';
export { default as Answer } from './Answer/Answer';
export { default as Tags } from './Tags/Tags';
export { default as Ask } from './Ask/Ask';
