const QUESTION_REPORT = {
  NOT_A_QUESTION: 'NOT_A_QUESTION',
  DUPLICATE: 'DUPLICATE',
  OFF_TOPIC: 'OFF_TOPIC',
  TOO_BROAD: 'TOO_BROAD',
  SPAM: 'SPAM',
  VIOLENCE: 'VIOLENCE',
  RACISM: 'RACISM',
  PORNOGRAPHY: 'PORNOGRAPHY',
  PERSONAL_DETAILS: 'PERSONAL_DETAILS',
};
const QUESTION_STATUS = {
  OPEN: 'OPEN',
  CLOSED: 'CLOSED',
  ON_HOLD: 'ON_HOLD',
  DELETED: 'DELETED',
};

export default {
  QUESTION_REPORT,
  QUESTION_STATUS,
};
