const ACCOUNT_STATUS = {
  ACTIVE: 'ACTIVE',
  SUSPENDED: 'SUSPENDED',
  BANNED: 'BANNED',
  BLOCKED: 'BLOCKED',
};

const ACCOUNT_ROLE = {
  BASIC: 'BASIC',
  MODULATOR: 'MODULATOR',
  ADMIN: 'ADMIN',
};
export default {
  ACCOUNT_STATUS,
  ACCOUNT_ROLE,
};
